[build]
  command = "yarn lint && yarn build"
  publish = "dist"

[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, s-max-age=86400"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, s-max-age=86400"

[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, s-max-age=86400"